### ISSUE TITLE
failure building with openssl@3, works with openssl@1.1

### ISSUE THREAD

**Issue by stepheneb** [gitx/objective-git#30]
Building gitx I  got this error building the ObjectiveGit.framework in xcode 13.2.1 on macos 11.6.3.

```
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_id", referenced from:
      __libssh2_ed25519_new_private_frommemory in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfile in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfilememory in libssh2.a(openssl.o)
ld: symbol(s) not found for architecture x86_64
```

Building succeeded adding LDFLAGS="-L/usr/local/opt/openssl@1.1/lib" to the ObjectiveGit.framework target build settings.

![image](https://user-images.githubusercontent.com/7188/153059617-b3d90aaf-16ca-4e52-a0c5-6d87494edb22.png)

see: https://github.com/gitx/gitx/issues/239#issuecomment-1032960138

**Comment by hannesa2** [comment]
When  I do this on my x86 Mac it still fails with same error.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/3314607/153070289-186f7804-7f2c-4b8d-a438-45638cc7d218.png">

To be able to verify your changes locally, please can you put your changes into a pull request ?

**Comment by stepheneb** [comment]
Have master checked out separately from gitx.

```
$ git show
commit 972f9aad0e276d30547fdb0a3b93e26407c29a2a (HEAD -> openssl1.1, origin/master, origin/HEAD, master)
Merge: 845bab0e 8f1da7a8
Author: Hannes Achleitner <hannes.achleitner@googlemail.com>
Date:   Sun Feb 6 16:23:55 2022 +0100

    Merge pull request #29 from gitx/Xcode_13.2.1
    
    Xcode 13.2.1
```

Opened `ObjectiveGitFramework.xcworkspace` in xcode 13.2.1 on macos 11.6.3 and got this error: `SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.`

![image](https://user-images.githubusercontent.com/7188/153080835-9a6956ac-dd9c-4e62-bc1e-f6dedadf54b3.png)

**Comment by hannesa2** [comment]
> Opened ObjectiveGitFramework.xcworkspace in xcode 13.2.1 on macos 11.6.3 and got this error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0.

I guess this should solved now with
* https://github.com/gitx/objective-git/pull/33
* https://github.com/gitx/objective-git/pull/34
* https://github.com/gitx/objective-git/pull/35 (With updated Swift version)

@stepheneb please give it a try on recent master

**Comment by hannesa2** [comment]
On my side your primary message disappeared after a simple
`brew reinstall openssl@3`

**Comment by stepheneb** [comment]
Got further:

- `error: no such file or directory: 'External/libssh2.a'`

Steps:

-  `brew reinstall openssl@3`.
- Checked out master branch in new dir.
- in dir: `git submodule update --init --recursive`
- open `ObjectiveGitFramework.xcworkspace` in xcode 13.2.1
- start build for my computer: macOS 11.6.3, MacBook Pro Retina, late 2013

```
Ld /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug/ObjectiveGit.framework/Versions/A/ObjectiveGit normal (in target 'ObjectiveGit-Mac' from project 'ObjectiveGitFramework')
    cd /Users/stephen/dev/macos/objgit/objective-git
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.9 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -L/Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug -L. -LExternal -L/usr/local/opt/openssl/lib -L/Users/stephen/dev/macos/objgit/objective-git/External/build/lib -F/Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug -filelist /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit.LinkFileList -install_name @rpath/ObjectiveGit.framework/ObjectiveGit -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -fapplication-extension -lgit2 -force_load External/libgit2.a External/libssh2.a -lcrypto -lssl -lcurl -lz -liconv -lgit2 -framework Cocoa -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_dependency_info.dat -o /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug/ObjectiveGit.framework/Versions/A/ObjectiveGit

clang: error: no such file or directory: 'External/libssh2.a'
Command Ld failed with a nonzero exit code
```

![image](https://user-images.githubusercontent.com/7188/153633795-a1a49180-991a-431a-9759-da27d2477d16.png)

**Comment by hannesa2** [comment]
you need to run `./script/bootstrap` in advance.

Wrong or not, I do all in command line

**Comment by stepheneb** [comment]
What are your commands to build completely from the command line?

After clone I presume they start like this:

```
git submodule update --init --recursive
./script/bootstrap
```

Now getting this error:

```
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_id", referenced from:
      __libssh2_ed25519_new_private_frommemory in libssh2.a(openssl.o)
```

More complete output from log:

```
Ld /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug/ObjectiveGit.framework/Versions/A/ObjectiveGit normal (in target 'ObjectiveGit-Mac' from project 'ObjectiveGitFramework')
    cd /Users/stephen/dev/macos/objgit/objective-git
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.9 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk -L/Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug -L. -LExternal -L/usr/local/opt/openssl/lib -L/Users/stephen/dev/macos/objgit/objective-git/External/build/lib -F/Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug -filelist /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit.LinkFileList -install_name @rpath/ObjectiveGit.framework/ObjectiveGit -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -object_path_lto -Xlinker /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fobjc-arc -fobjc-link-runtime -fapplication-extension -lgit2 -force_load External/libgit2.a External/libssh2.a -lcrypto -lssl -lcurl -lz -liconv -lgit2 -framework Cocoa -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ObjectiveGitFramework.build/Debug/ObjectiveGit-Mac.build/Objects-normal/x86_64/ObjectiveGit_dependency_info.dat -o /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Products/Debug/ObjectiveGit.framework/Versions/A/ObjectiveGit

ld: warning: dylib (/usr/local/opt/openssl/lib/libcrypto.dylib) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: dylib (/usr/local/opt/openssl/lib/libssl.dylib) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: linking against a dylib which is not safe for use in application extensions: /usr/local/opt/openssl/lib/libcrypto.dylib
ld: warning: linking against a dylib which is not safe for use in application extensions: /usr/local/opt/openssl/lib/libssl.dylib
ld: warning: object file (External/libssh2.a(agent.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(channel.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(global.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(hostkey.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(session.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(userauth.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(misc.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(openssl.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(kex.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(packet.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(transport.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(keepalive.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(comp.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(mac.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(pem.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(bcrypt_pbkdf.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(crypt.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(blowfish.o)) was built for newer macOS version (11.0) than being linked (10.9)
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_id", referenced from:
      __libssh2_ed25519_new_private_frommemory in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfile in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfilememory in libssh2.a(openssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by hannesa2** [comment]
I do almost the same like this https://github.com/gitx/objective-git/blob/master/.github/workflows/BuildPR.yml#L21-L24

But I only build `arm64` (I use a M1) without `x86_64`
```
script/bootstrap && script/update_libgit2
xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test archive ARCHS="arm64"
```

**Comment by hannesa2** [comment]
I could swear, it was working before lunch, but the test doesn't work anymore, but this works

`xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive ARCHS="arm64" `

<img width="744" alt="image" src="https://user-images.githubusercontent.com/3314607/153637903-1d58de04-439a-47cc-8901-d96bd0b3c4a9.png">

### This is all dirty :
![image](https://user-images.githubusercontent.com/3314607/153637855-ec5bae37-cc4d-4d43-a43b-bfa54ad354d3.png)

And should be solved only by (architecture dependent) search path. I spent the half day with this, but still no success...

What's your output of  `find /opt/homebrew -name "libssh*.a"` ?

**Comment by hannesa2** [comment]
Ahh, on your side the output of `find /usr/local -name "libssh*.a"` ?

**Comment by stepheneb** [comment]
```
$ find /usr/local -name "libssh*.a"
/usr/local/lib/libssh2.a
/usr/local/Cellar/libssh2/1.10.0/lib/libssh2.a

$ ls -l /usr/local/lib/libssh2.a
lrwxr-xr-x  1 stephen  admin  38 Sep 27 11:18 /usr/local/lib/libssh2.a -> ../Cellar/libssh2/1.10.0/lib/libssh2.a
```

In tests below I am now doing this to setup for building:

```
git clone git@github.com:gitx/objective-git.git
cd objective-git
git submodule update --init --recursive
script/bootstrap && script/update_libgit2
```

Then tried with and without `test` in the `xcodebuild` invocation:


```
xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" test archive ARCHS="x86_64"
```
Same error when building in xcode app:
```
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_id", referenced from:
      __libssh2_ed25519_new_private_frommemory in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfile in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfilememory in libssh2.a(openssl.o)
ld: symbol(s) not found for architecture x86_64
```

```
xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive ARCHS="x86_64"
```
Different (but probably related??):
```
** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/stephen/Library/Developer/Xcode/DerivedData/ObjectiveGitFramework-fyaphaesxegukpfgkwopelgpztry/Build/Intermediates.noindex/ArchiveIntermediates/ObjectiveGit\ Mac/IntermediateBuildFilesPath/UninstalledProducts/macosx/ObjectiveGit.framework/Versions/A/ObjectiveGit normal (in target 'ObjectiveGit-Mac' from project 'ObjectiveGitFramework')
```

**Comment by hannesa2** [comment]
And do you have these files ? `find . -name "libss*.a" | xargs ls -la`

<img width="631" alt="image" src="https://user-images.githubusercontent.com/3314607/153668919-5413f105-2c2f-422b-bf28-b4416bb6ee75.png">

**Comment by stepheneb** [comment]
I only seem to have: `./External/libssh2.a`

```
[objective-git  (master)]$ find . -name "libss*.a" | xargs ls -la
-r--r--r--  1 stephen  staff  295272 Feb 11 12:24 ./External/libssh2.a
[objective-git ruby-2.7.5 (master)]$ 
```

**Comment by hannesa2** [comment]
Ahh sorry, this was a pointer into the wrong direction. It was a leftover from an other try. You don't need it
This is how it looks like on my side
![image](https://user-images.githubusercontent.com/3314607/153702486-8ca5af67-309d-4d3f-a5d2-20a7e38fc356.png)

I tried it again in a new directory, without `test` (don't work for locally for arm64) and for `arm64` (CI does it with `x86_64`)
```
git clone git@github.com:gitx/objective-git.git
cd objective-git
git submodule update --init --recursive
script/bootstrap && script/update_libgit2
xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive ARCHS="arm64" | tee outputARM64.log`
```
<img width="282" alt="image" src="https://user-images.githubusercontent.com/3314607/153702874-2f65bf28-dd24-4753-a151-b9a56a86ed79.png">

For me it looks like the issue is somehow related outside of the repo ? brew ?

Please can you share your output [outputARM64.log](https://github.com/gitx/objective-git/files/8053031/outputARM64.log) to be able todo a file compare.

**Comment by stepheneb** [comment]
I've attached `outputARM64.log`. The build seems to have completed successfully. Building with `ARCHS="x86_64"` still fails as it did before.

```
cd ..
rm -rf objective-git
git clone git@github.com:gitx/objective-git.git && cd objective-git
git submodule update --init --recursive
script/bootstrap && script/update_libgit2
xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive ARCHS="arm64" | tee outputARM64.log
```
[outputARM64.log](https://github.com/gitx/objective-git/files/8053930/outputARM64.log)

FYI: here's what's in `./External`:

```
$ tree -L 1 External/
External/
|-- libextobjc
|-- libgit2
|-- libgit2.a
|-- libssh2
|-- libssh2.a
`-- openssl
```

**Comment by hannesa2** [comment]
Hmm, I guess you need to run
`
xcodebuild -workspace ObjectiveGitFramework.xcworkspace -scheme "ObjectiveGit Mac" archive ARCHS="x86_64" | tee outputx86_64.log`

or do you own an Apple Silicon ?

**Comment by stepheneb** [comment]
Don't have a newer mac.

Here's the `ARCHS="x86_64"` log: [outputx86_64.log](https://github.com/gitx/objective-git/files/8054011/outputx86_64.log)

**Comment by hannesa2** [comment]
I see this as a probably major issue 
<img width="944" alt="image" src="https://user-images.githubusercontent.com/3314607/153722019-e7fe205b-56a0-4545-af2c-13dafbf01be2.png">

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../libgit2.a(auth_negotiate.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../libgit2.a(winhttp.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../libgit2.a(auth_negotiate.c.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../libgit2.a(winhttp.c.o) has no symbols
```

Which ends into this finally

```
ld: warning: object file (External/libssh2.a(crypt.o)) was built for newer macOS version (11.0) than being linked (10.9)
ld: warning: object file (External/libssh2.a(blowfish.o)) was built for newer macOS version (11.0) than being linked (10.9)
Undefined symbols for architecture x86_64:
  "_EVP_PKEY_id", referenced from:
      __libssh2_ed25519_new_private_frommemory in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfile in libssh2.a(openssl.o)
      __libssh2_pub_priv_keyfilememory in libssh2.a(openssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

The big question is: **Why do your objects have no symbols ?** 
It's only related to your local machine, because CI can build and link it

**Comment by stepheneb** [comment]
Thanks for all the help.

Do you have an `x86_64` mac? If so can you attach a log from your build that is successful. 

Does `./External/libgit2.a` in your build dir have symbols for `auth_negotiate` and `winhttp`?

```
$ nm -gC ./External/libgit2.a | grep auth_negotiate
./External/libgit2.a:auth_negotiate.c.o: no symbols
./External/libgit2.a(auth_negotiate.c.o):
./External/libgit2.a:winhttp.c.o: no symbols
```

I also noticed in the last `clang` invocation which generates the `Undefined symbols for architecture x86_64: "_EVP_PKEY_id"` error  a nonexistent directory is included.

```
ld: warning: directory not found for option '-L/Users/stephen/dev/macos/objgit/objective-git/External/build/lib'
```

**Comment by hannesa2** [comment]
### arm64

<img width="809" alt="image" src="https://user-images.githubusercontent.com/3314607/153727725-c925f05a-a971-415a-bb35-390cebaafae6.png">

**Comment by hannesa2** [comment]
### local x86

(today I've access)

<img width="779" alt="image" src="https://user-images.githubusercontent.com/3314607/153728119-e3e53390-9c8a-4048-a5fd-9fc66abba4bb.png">

Unfortunately the same like on your local machine 

### CI x86

https://github.com/hannesa2/objective-git/pull/39

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3314607/153728564-4cd7cded-0921-4bfb-9aa3-6373ecc29b20.png">

<img width="509" alt="image" src="https://user-images.githubusercontent.com/3314607/153728578-49fddc33-fe8d-4526-957b-4a60cd7e5854.png">

Sorry, I don't understand why CI builds properly.

**Comment by hannesa2** [comment]
Ci comes only with `openssl@1.1` only !
<img width="338" alt="image" src="https://user-images.githubusercontent.com/3314607/153729246-3f666166-f099-4318-b4ae-d4d8b2436541.png">

So I removed local 
`brew remove openssl@3`

and now, it looks like different

<img width="796" alt="image" src="https://user-images.githubusercontent.com/3314607/153729273-217e8c9b-c8bb-4fe1-b9d5-56cda9fab559.png">

This missing openssl directory is interesting ...

**Comment by hannesa2** [comment]
I made it work locally ! Thank you, this ticket helped me to understand the problem, even https://github.com/gitx/gitx/issues/239 works now.

Btw, there is no reason to `brew remove openssl@3` anymore

**Comment by stepheneb** [comment]
Just tried again from scratch and the objective-git build also works for me! Thanks for your hard work!
